# Generated by Django 4.2.2 on 2024-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donors_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='ph_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
