# Generated by Django 4.2.2 on 2024-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donors_ph_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='active_status',
            field=models.ImageField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=10, upload_to=''),
        ),
    ]
