# Generated by Django 4.2.2 on 2024-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_donors_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='donors',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
