# Generated by Django 4.2.2 on 2024-02-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_donors_profile_img_donors_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='verified',
        ),
    ]
