# Generated by Django 4.2.2 on 2024-02-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_donors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='profile_there',
        ),
    ]
