# Generated by Django 4.2.2 on 2024-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_donors_profile_there'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='blood_group',
            field=models.CharField(choices=[('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B -ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve'), ('A1 +ve', 'A1 +ve'), ('A1 -ve', 'A1 -ve'), ('A1B +ve', 'A1 +ve'), ('A1B -ve', 'A1 -ve'), ('A2 +ve', 'A2 +ve'), ('A2 -ve', 'A2 -ve'), ('A2B +ve', 'A2B +ve'), ('A2B -ve', 'A2B -ve'), ('INRA', 'INRA'), ('Bombay Blood Group', 'Bombay Blood Group')], max_length=20),
        ),
    ]
